import { t } from './i18n.js';
import { getClient } from './supa.js';
import { currentUser } from './auth.js';

// BEGIN README CARD THEMES
// Source: https://github.com/anuraghazra/github-readme-stats/blob/master/themes/index.js
// Generated by scripts/generate-card-themes.mjs
// MIT License
//
// Copyright (c) 2020 Anurag Hazra
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
const readmeCardThemes = {
  "readme-default": ["#fffefe","#fffefe","#434d58","#2f80ed"],
  "readme-default_repocard": ["#fffefe","#fffefe","#434d58","#2f80ed"],
  "readme-transparent": ["#ffffff","#ffffff","#417e87","#006aff"],
  "readme-shadow_red": ["#ffffff","#ffffff","#444444","#9a0000"],
  "readme-shadow_green": ["#ffffff","#ffffff","#444444","#007a00"],
  "readme-shadow_blue": ["#ffffff","#ffffff","#444444","#00779a"],
  "readme-dark": ["#151515","#151515","#9f9f9f","#ffffff"],
  "readme-radical": ["#141321","#141321","#a9fef7","#fe428e"],
  "readme-merko": ["#0a0f0b","#0a0f0b","#68b587","#abd200"],
  "readme-gruvbox": ["#282828","#282828","#8ec07c","#fabd2f"],
  "readme-gruvbox_light": ["#fbf1c7","#fbf1c7","#427b58","#b57614"],
  "readme-tokyonight": ["#1a1b27","#1a1b27","#38bdae","#70a5fd"],
  "readme-onedark": ["#282c34","#282c34","#df6d74","#e4bf7a"],
  "readme-cobalt": ["#193549","#193549","#75eeb2","#e683d9"],
  "readme-synthwave": ["#2b213a","#2b213a","#e5289e","#e2e9ec"],
  "readme-highcontrast": ["#000000","#000000","#ffffff","#e7f216"],
  "readme-dracula": ["#282a36","#282a36","#f8f8f2","#ff6e96"],
  "readme-prussian": ["#172f45","#172f45","#6e93b5","#bddfff"],
  "readme-monokai": ["#272822","#272822","#f1f1eb","#eb1f6a"],
  "readme-vue": ["#fffefe","#fffefe","#273849","#41b883"],
  "readme-vue-dark": ["#273849","#273849","#fffefe","#41b883"],
  "readme-shades-of-purple": ["#2d2b55","#2d2b55","#a599e9","#fad000"],
  "readme-nightowl": ["#011627","#011627","#7fdbca","#c792ea"],
  "readme-buefy": ["#ffffff","#ffffff","#363636","#7957d5"],
  "readme-blue-green": ["#040f0f","#040f0f","#0cf574","#2f97c1"],
  "readme-algolia": ["#050f2c","#050f2c","#ffffff","#00aeff"],
  "readme-great-gatsby": ["#000000","#000000","#ffd95b","#ffa726"],
  "readme-darcula": ["#242424","#242424","#bebebe","#ba5f17"],
  "readme-bear": ["#1f2023","#1f2023","#bcb28d","#e03c8a"],
  "readme-solarized-dark": ["#002b36","#002b36","#859900","#268bd2"],
  "readme-solarized-light": ["#fdf6e3","#fdf6e3","#859900","#268bd2"],
  "readme-chartreuse-dark": ["#000000","#000000","#ffffff","#7fff00"],
  "readme-nord": ["#2e3440","#2e3440","#d8dee9","#81a1c1"],
  "readme-gotham": ["#0c1014","#0c1014","#99d1ce","#2aa889"],
  "readme-material-palenight": ["#292d3e","#292d3e","#a6accd","#c792ea"],
  "readme-graywhite": ["#ffffff","#ffffff","#24292e","#24292e"],
  "readme-vision-friendly-dark": ["#000000","#000000","#ffffff","#ffb000"],
  "readme-ayu-mirage": ["#1f2430","#1f2430","#c7c8c2","#f4cd7c"],
  "readme-midnight-purple": ["#000000","#000000","#ffffff","#9745f5"],
  "readme-calm": ["#373f51","#373f51","#ebcfb2","#e07a5f"],
  "readme-flag-india": ["#ffffff","#ffffff","#509e2f","#ff8f1c"],
  "readme-omni": ["#191622","#191622","#e1e1e6","#ff79c6"],
  "readme-react": ["#20232a","#20232a","#ffffff","#61dafb"],
  "readme-jolly": ["#291b3e","#291b3e","#ffffff","#ff64da"],
  "readme-maroongold": ["#260000","#260000","#e0aa3e","#f7ef8a"],
  "readme-yeblu": ["#002046","#002046","#ffffff","#ffff00"],
  "readme-blueberry": ["#242938","#242938","#27e8a7","#82aaff"],
  "readme-slateorange": ["#36393f","#36393f","#ffffff","#faa627"],
  "readme-kacho_ga": ["#402b23","#402b23","#d9c8a9","#bf4a3f"],
  "readme-outrun": ["#141439","#141439","#8080ff","#ffcc00"],
  "readme-ocean_dark": ["#151a28","#151a28","#92d534","#8957b2"],
  "readme-city_lights": ["#1d252c","#1d252c","#718ca1","#5d8cb3"],
  "readme-github_dark": ["#0d1117","#0d1117","#c3d1d9","#58a6ff"],
  "readme-github_dark_dimmed": ["#24292f","#24292f","#adbac7","#539bf5"],
  "readme-discord_old_blurple": ["#2c2f33","#2c2f33","#ffffff","#7289da"],
  "readme-aura_dark": ["#252334","#252334","#dbdbdb","#ff7372"],
  "readme-panda": ["#31353a","#31353a","#ff75b5","#19f9d8"],
  "readme-noctis_minimus": ["#1b2932","#1b2932","#c5cdd3","#d3b692"],
  "readme-cobalt2": ["#193549","#193549","#0088ff","#ffc600"],
  "readme-swift": ["#f7f7f7","#f7f7f7","#000000","#000000"],
  "readme-aura": ["#15141b","#15141b","#61ffca","#a277ff"],
  "readme-apprentice": ["#262626","#262626","#bcbcbc","#ffffff"],
  "readme-moltack": ["#f5e1c0","#f5e1c0","#574038","#86092c"],
  "readme-codeSTACKr": ["#09131b","#09131b","#ffffff","#ff652f"],
  "readme-rose_pine": ["#191724","#191724","#e0def4","#9ccfd8"],
  "readme-catppuccin_latte": ["#eff1f5","#eff1f5","#4c4f69","#137980"],
  "readme-catppuccin_mocha": ["#1e1e2e","#1e1e2e","#cdd6f4","#94e2d5"],
  "readme-date_night": ["#170f0c","#170f0c","#e1b2a2","#da7885"],
  "readme-one_dark_pro": ["#23272e","#23272e","#e5c06e","#61afef"],
  "readme-rose": ["#e9d8d4","#e9d8d4","#862931","#8d192b"],
  "readme-holi": ["#030314","#030314","#d6e7ff","#5fabee"],
  "readme-neon": ["#000000","#000000","#ff449f","#00ead3"],
  "readme-blue_navy": ["#000000","#000000","#82aaff","#82aaff"],
  "readme-calm_pink": ["#2b2d40","#2b2d40","#edae49","#e07a5f"],
  "readme-ambient_gradient": ["#4158d0","#ffcc70","#ffffff","#ffffff"]
};
// END README CARD THEMES

export const themes = { midnight: t("ミッドナイト"), paper: t("ペーパー"), aurora: t("オーロラ"), mono: t("Mono"), ghost: t("Ghost"), spring: t("春"), summer: t("夏"), autumn: t("秋"), winter: t("冬"), ...Object.fromEntries(Object.keys(readmeCardThemes).map(key => [key, key.slice(7)])) };
export const baseColors = [['#18181b',t("チャコール")],['#1d4ed8',t("ブルー")],['#4f46e5',t("インディゴ")],['#7c3aed',t("パープル")],['#be185d',t("ピンク")],['#b91c1c',t("レッド")],['#c2410c',t("オレンジ")],['#0f766e',t("ティール")],['#15803d',t("グリーン")],['#f4e8d0',t("アイボリー")],['#e5e7eb',t("グレー")],['#ffffff',t("ホワイト")]];
export function paletteFromBase(value, pattern = 'gradient', theme = 'midnight') {
  const frontColor = /^#[0-9a-f]{6}$/i.test(value) ? value.toLowerCase() : '#18181b';
  const rgb = frontColor.slice(1).match(/../g).map(v => parseInt(v,16));
  let back = pattern === 'solid' ? rgb : rgb.map(v => Math.round(v * 0.45));
  if (theme === 'aurora' && pattern !== 'solid') {
    const [r,g,b] = rgb.map(v => v / 255), max = Math.max(r,g,b), min = Math.min(r,g,b), delta = max-min;
    let hue = delta === 0 ? 0 : max === r ? ((g-b)/delta+6)%6 : max === g ? (b-r)/delta+2 : (r-g)/delta+4;
    hue = (hue + 1.67) % 6;
    const saturation = Math.max(0.6, max === 0 ? 0 : delta/max), brightness = Math.max(0.55,max*0.85);
    const c = brightness*saturation, x = c*(1-Math.abs(hue%2-1)), m = brightness-c;
    const channels = hue<1?[c,x,0]:hue<2?[x,c,0]:hue<3?[0,c,x]:hue<4?[0,x,c]:hue<5?[x,0,c]:[c,0,x];
    back = channels.map(v => Math.round((v+m)*255));
  }
  const luminance = values => values.map(v => { const c = v / 255; return c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4; }).reduce((sum,v,i) => sum + v * [0.2126,0.7152,0.0722][i],0);
  const textColor = 1.05 / (luminance(rgb) + 0.05) >= (luminance(back) + 0.05) / 0.05 ? '#ffffff' : '#000000';
  return { frontColor, backColor: '#' + back.map(v => v.toString(16).padStart(2,'0')).join(''), textColor, accentColor: textColor };
}
export function defaultDesign(theme = 'midnight', layout = 'classic') {
  const extras = { mono:['#18181b','#3f3f46','#fafafa','#d4d4d8'], ghost:['#e8edf5','#b8c5dc','#172033','#566887'], spring:['#ffe4ed','#d9efde','#482c3c','#9b4766'], summer:['#cffafe','#38bdf8','#083344','#075985'], autumn:['#ffedd5','#d97706','#431407','#7c2d12'], winter:['#eff6ff','#a5c7e7','#172554','#36588a'] };
  const palette = (Object.hasOwn(readmeCardThemes, theme) ? readmeCardThemes[theme] : undefined) ?? extras[theme] ?? (theme === 'paper' ? ['#fffdf4','#e7dfca','#29251f','#876c37']
    : theme === 'aurora' ? ['#34265b','#187e80','#f8fafc','#91efdf'] : ['#222e49','#0b1020','#f8fafc','#9fb5ef']);
  return { frontColor: palette[0], backColor: palette[1], textColor: palette[2], accentColor: palette[3],
    font: theme === 'mono' ? 'mono' : 'sans', nameSize: 26, radius: 18, pattern: 'gradient', frontAlign: layout, backAlign: layout,
    frontLabel: 'SPOTCODE / BUSINESS CARD', backLabel: 'LET’S CONNECT', orientation: 'landscape', cornerStyle: 'rounded', imagePlacement: 'inline' };
}
export const cardLayerKinds = ['frontLabel','name','title','image','bio','contact','links','backLabel'];
export function normalizeCardLayers(layers) {
  if (!Array.isArray(layers)) return undefined;
  const seen = new Set();
  const bound = (n, low, high, fallback) => Number.isFinite(Number(n)) ? Math.min(high, Math.max(low, Number(n))) : fallback;
  return layers.slice(0,16).filter(l => l && cardLayerKinds.includes(l.kind) && !seen.has(l.kind) && seen.add(l.kind)).map(l => {
    const width = bound(l.width,5,100,80), height = bound(l.height,5,100,16);
    return {kind:l.kind,side:l.side==='back'?'back':'front',x:bound(l.x,0,100-width,0),y:bound(l.y,0,100-height,0),
      width,height,rotation:bound(l.rotation,-180,180,0),fontSize:bound(l.fontSize,6,72,14),hidden:l.hidden===true,locked:l.locked===true};
  });
}
export function defaultCardLayers(card) {
  const layer = (kind,side,x,y,width,height,fontSize=14) => ({kind,side,x,y,width,height,fontSize,rotation:0,hidden:false,locked:false});
  return [layer('frontLabel','front',8,8,84,10,9),layer('name','front',8,28,62,20,card.design?.nameSize ?? 26),
    layer('title','front',8,51,62,18),layer('image',card.image_side ?? 'front',74,28,18,30),
    layer('links',card.links_side ?? 'front',8,76,84,18,10),layer('backLabel','back',8,8,84,10,9),
    layer('bio','back',8,28,84,36),layer('contact','back',8,70,84,20,12)];
}
export function normalizeDesign(value, theme, layout) {
  const defaults = defaultDesign(theme, layout);
  const d = value && typeof value === 'object' ? value : {};
  const result = { ...defaults };
  if (Object.hasOwn(themes, d.themeVariant)) result.themeVariant = d.themeVariant;
  for (const key of ['frontColor','backColor','textColor','accentColor']) {
    if (/^#[0-9a-f]{6}$/i.test(d[key])) result[key] = d[key];
  }
  for (const [key, allowed] of Object.entries({imagePlacement:['inline','artwork'],orientation:['landscape','portrait'],cornerStyle:['rounded','square','diagonal','diagonalReverse'],font:['sans','serif','mono'],pattern:['solid','gradient','stripe'],frontAlign:['classic','centered','right'],backAlign:['classic','centered','right']})) {
    if (allowed.includes(d[key])) result[key] = d[key];
  }
  for (const [key,min,max] of [['nameSize',18,36],['radius',0,28]]) {
    if (d[key] !== '' && d[key] != null && Number.isFinite(Number(d[key]))) result[key] = Math.round(Math.min(max,Math.max(min,Number(d[key]))));
  }
  for (const key of ['frontLabel','backLabel']) if (typeof d[key] === 'string') result[key] = d[key].slice(0,40);
  if (Array.isArray(d.layers)) result.layers = normalizeCardLayers(d.layers);
  return result;
}
export function cardWebURL(value) {
  const raw = String(value ?? '').trim();
  if (!raw || raw.length > 2048) return '';
  try {
    const u = new URL(raw);
    return ['https:', 'http:'].includes(u.protocol) && !u.username && !u.password ? u.href : '';
  } catch { return ''; }
}
export function cardImageURL(value) {
  const raw = String(value ?? '').trim();
  if (raw.length > 1000000) return '';
  return /^data:image\/(?:jpeg|png|webp);base64,[a-z0-9+/=]+$/i.test(raw) ? raw : cardWebURL(raw);
}
function inputLinks(value) {
  if (Object.hasOwn(value, 'link_0_url')) return [0,1,2].map(i => ({ label: value['link_' + i + '_label'], url: value['link_' + i + '_url'] }));
  return Array.isArray(value.links) ? value.links.slice(0,3) : [];
}
export function normalizeCard(value = {}) {
  const text = (key, max) => String(value[key] ?? '').trim().slice(0, max);
  const design = { ...(value.design || {}) };
  const theme = Object.hasOwn(themes, design.themeVariant) ? design.themeVariant : value.theme;
  for (const key of Object.keys(defaultDesign())) if (Object.hasOwn(value, 'design_' + key)) design[key] = value['design_' + key];
  const links = inputLinks(value).map(link => ({ label: String(link?.label ?? '').trim().slice(0,40), url: cardWebURL(link?.url) })).filter(link => link.url);
  return { image_url: cardImageURL(value.image_url), image_link: cardWebURL(value.image_link),
    image_side: value.image_side === 'back' ? 'back' : 'front', image_shape: value.image_shape === 'round' ? 'round' : 'square',
    image_size: Number.isFinite(Number(value.image_size)) && value.image_size !== '' && value.image_size != null ? Math.round(Math.max(48, Math.min(100, Number(value.image_size)))) : 64,
    links_side: value.links_side === 'back' ? 'back' : 'front', links, design: normalizeDesign(design, theme, value.layout), name: text('name', 60), title: text('title', 100), bio: text('bio', 280), contact: text('contact', 160),
    theme: Object.hasOwn(themes, theme) ? theme : 'midnight',
    layout: value.layout === 'centered' ? 'centered' : 'classic' };
}
export function cardLink(handle) {
  return 'https://hrmcngs.github.io/spotcode-sns/#/' + encodeURIComponent(handle) + '/card';
}
function check(result) {
  if (result.error) throw new Error(t("名刺を読み込み・保存できませんでした。接続を確認して再試行してください。"));
  return result.data;
}
function actor() {
  const me = currentUser();
  if (!me?.id) throw new Error(t("ログインしてください。"));
  return me.id;
}
export async function loadCard(handle) {
  const db = await getClient();
  const profile = check(await db.from('profiles').select('id,handle,name').eq('handle', handle).maybeSingle());
  if (!profile) throw new Error(t("ユーザーが見つかりません。"));
  const viewer = currentUser()?.id;
  if (viewer !== profile.id) {
    if (!viewer) return { profile, card: null, restricted: true };
    const saved = check(await db.from('business_card_collection').select('card_owner_id')
      .eq('collector_id', viewer).eq('card_owner_id', profile.id).maybeSingle());
    if (!saved) return { profile, card: null, restricted: true };
  }
  const card = check(await db.from('business_cards').select('*').eq('owner_id', profile.id).maybeSingle());
  return { profile, card };
}
export async function saveCard(value) {
  const owner_id = actor();
  for (const link of [...inputLinks(value), { url: value.image_link }]) {
    if (String(link?.url ?? '').trim() && !cardWebURL(link.url)) throw new Error(t("リンクは http:// または https:// から始まるURLを入力してください。"));
  }
  if (String(value.image_url ?? '').trim() && !cardImageURL(value.image_url)) throw new Error(t("画像を選び直すか、http(s)形式の画像URLを入力してください。"));
  const card = normalizeCard(value);
  if (!['midnight','paper','aurora'].includes(card.theme)) {
    card.design.themeVariant = card.theme;
    card.theme = 'midnight';
  }
  if (!card.name) throw new Error(t("名刺に表示する名前を入力してください。"));
  const db = await getClient();
  return check(await db.from('business_cards').upsert({ ...card, owner_id }).select().single());
}
export async function collectCard(owner_id) {
  const collector_id = actor();
  if (collector_id === owner_id) throw new Error(t("自分の名刺はコレクションに追加できません。"));
  const db = await getClient();
  check(await db.from('business_card_collection').upsert({ collector_id, card_owner_id: owner_id },
    { onConflict: 'collector_id,card_owner_id', ignoreDuplicates: true }));
}
export async function removeCard(owner_id) {
  const collector_id = actor();
  const db = await getClient();
  check(await db.from('business_card_collection').delete().eq('collector_id', collector_id).eq('card_owner_id', owner_id));
}
export async function unpublishCard() {
  const owner_id = actor();
  const db = await getClient();
  check(await db.from('business_cards').delete().eq('owner_id', owner_id));
}
export async function loadCollection() {
  const collector_id = actor();
  const db = await getClient();
  return check(await db.from('business_card_collection')
    .select('card_owner_id,collected_at,card:business_cards(*,profile:profiles(handle))')
    .eq('collector_id', collector_id).order('collected_at', { ascending: false }));
}
