#!/usr/bin/env sbcl --script
;;; Test real keychain persistence across signed rebuilds using fixture bytes only.
(require :asdf)
(defparameter *scripts* (uiop:pathname-directory-pathname *load-truename*))
(defparameter *root* (truename (merge-pathnames "../" *scripts*)))
(defun run-text (&rest args)
  (string-trim '(#\Space #\Newline #\Return) (uiop:run-program args :output :string :error-output :interactive)))
(defun replace-all (text old new)
  (with-output-to-string (out)
    (loop with from = 0 for found = (search old text :start2 from)
          do (write-string text out :start from :end found)
          while found do (write-string new out) (setf from (+ found (length old))))))
(defun xml-text (text)
  (reduce (lambda (value pair) (replace-all value (car pair) (cdr pair)))
          '(("&" . "&amp;") ("<" . "&lt;") (">" . "&gt;") ("\"" . "&quot;")) :initial-value text))
(defun main ()
  (let* ((app (namestring (merge-pathnames "macos/build-preview/Build/Products/Debug-maccatalyst/App.app/" *root*)))
         (info (concatenate 'string app "Contents/Info.plist"))
         (bundle (run-text "/usr/libexec/PlistBuddy" "-c" "Print :CFBundleIdentifier" info))
         (group (run-text "/usr/libexec/PlistBuddy" "-c" "Print :SpotcodeKeychainAccessGroup" info))
         (identity (multiple-value-bind (output errors)
                       (uiop:run-program (list "codesign" "-dv" "--verbose=4" app) :output :string :error-output :string)
                     (declare (ignore output))
                     (loop for line in (uiop:split-string errors :separator '(#\Newline))
                           when (uiop:string-prefix-p "Authority=" line) return (subseq line 10))))
         (account (concatenate 'string "persistence-regression." (run-text "uuidgen")))
         (folder (uiop:ensure-directory-pathname (run-text "mktemp" "-d" (concatenate 'string (namestring (uiop:temporary-directory)) "spotcode-keychain-rebuild.XXXXXX"))))
         (probe (namestring (merge-pathnames "Probe.app/" folder)))
         (executable (namestring (merge-pathnames "Probe.app/Contents/MacOS/Probe" folder)))
         (entitlements (namestring (merge-pathnames "probe.entitlements" folder)))
         (swift (merge-pathnames "Probe.swift" folder))
         (wrote nil))
    (unwind-protect
         (progn
           (unless identity (error "A development-signed macOS preview build is required."))
           (ensure-directories-exist executable)
           (with-open-file (out (merge-pathnames "Probe.app/Contents/Info.plist" folder) :direction :output :if-exists :supersede)
             (format out "<?xml version=~S encoding=~S?><plist version=~S><dict><key>CFBundleIdentifier</key><string>~A</string><key>CFBundleExecutable</key><string>Probe</string><key>CFBundlePackageType</key><string>APPL</string><key>CFBundleVersion</key><string>1</string><key>SpotcodeKeychainAccessGroup</key><string>~A</string></dict></plist>"
                     "1.0" "UTF-8" "1.0" (xml-text bundle) (xml-text group)))
           (let ((profile (concatenate 'string app "Contents/embedded.provisionprofile")))
             (when (probe-file profile) (uiop:copy-file profile (merge-pathnames "Probe.app/Contents/embedded.provisionprofile" folder))))
           (uiop:copy-file (merge-pathnames "macos/build-preview/Build/Intermediates.noindex/App.build/Debug-maccatalyst/App.build/App.app.xcent" *root*) entitlements)
           (flet ((build-probe (version)
                    (with-open-file (out swift :direction :output :if-exists :supersede :external-format :utf-8)
                      (write-string (replace-all (uiop:read-file-string (merge-pathnames "ios/App/App/KeychainStore.swift" *root*) :external-format :utf-8)
                                                 "#if targetEnvironment(macCatalyst)" "#if KEYCHAIN_PROBE") out)
                      (format out "~%let probeBuild = ~D~%" version)
                      (write-string (uiop:read-file-string (merge-pathnames "ios-tests/signed-keychain.swift" *scripts*) :external-format :utf-8) out))
                    (uiop:run-program (list "xcrun" "swiftc" "-D" "KEYCHAIN_PROBE" "-module-cache-path" (namestring (merge-pathnames "cache/" folder)) (namestring swift) "-o" executable) :output :interactive :error-output :interactive)
                    (run-text "codesign" "--force" "--sign" identity "--entitlements" entitlements "--generate-entitlement-der" "--timestamp=none" probe)
                    (run-text "codesign" "--verify" "--strict" probe)))
             (build-probe 1)
             (uiop:run-program (list executable "write" account) :output :interactive)
             (setf wrote t)
             (build-probe 2)
             (uiop:run-program (list executable "read" account) :output :interactive)
             (format t "PASS real keychain survives signed rebuild; no login tokens accessed.~%")))
      (unwind-protect
           (when wrote (uiop:run-program (list executable "delete" account) :output :interactive))
        (uiop:delete-directory-tree folder :validate t)))))
(handler-case (main)
  (error (condition) (format *error-output* "~&Signed keychain test failed: ~A~%" condition) (uiop:quit 1)))
